#Nome do arquivo deve estar com letra minuscula e deve ser o mesmo
#que está no nome do app em main.py
<incrementador>: #precisa estar entre <> para chamar a funcao do main.py
    orientation:'vertical'
    Button:
        text:'Incrementar' 
        font_size:30
        on_release:texto_botao.text = str(int(texto_botao.text)+1)
        #Acesso a variavel atraves do id e então acesso outros niveis
    Label:
        id:texto_botao  #Serve para acessar os dados do widget em outras partes do codigo
        text:'1'
        